language: perl
perl:
    - "5.8"
    - "5.10"
    - "5.12"
    - "5.14"
    - "5.18"
    - "5.20"
    - "5.22"
sudo:
  false
before_install:
    - git clone git://github.com/haarg/perl-travis-helper
    - source perl-travis-helper/init
    - build-perl
    - perl -V
install:
    - cpanm Term::ProgressBar Log::Log4perl FindBin Pod::Usage Devel::Cover Devel::Cover::Report::Coveralls
script:
    - PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove -lrv t/*.t
after_success:
    - cover
    - cove -report coveralls
matrix:
    allow_failures:
       - perl: "5.8"